### ISSUE TITLE
Support Confluent version 6.2.5

### ISSUE THREAD

**Issue by bm1549** [arm64-compat/confluent-platform#7]
First of all, thank you for creating this. I found it on [this thread](https://github.com/confluentinc/kafka-images/issues/80#issuecomment-1108911026) and it's saved so much time and effort with developing on M1

I am currently still on the 6.x major version of Confluent and wanted to use 6.2.5, but noticed that an image wasn't available from your registry. Would it be okay to update [.gitmodules](https://github.com/arm64-compat/confluent-platform/blob/main/.gitmodules) in a 6.x branch in this repo to build that image? If not, is there any other way I can help to update the pipeline to support parallel major versions?

**Comment by sjucovschi** [comment]
Hi @anuragagarwal561994 and @bm1549. 
First of all, thank you @anuragagarwal561994 for this project. In the company I work for, we use Confluent and because many of us received new M1 macs, your project is a life saver!!

I also want to offer my help and I could try to create a PR for version 7.2.0 . Please let me know if this would be ok and if there is another way I could help.

**Comment by altaiezior** [comment]
@bm1549 let me give it a try

**Comment by altaiezior** [comment]
@bm1549 I checked it, the versions as listed by the official confluent repo has some vulnerabilities. I guess support for version 6.2.5 can be provided but as earlier stated please make sure that the image is used only in local and that it would expose some vulnerabilities.

**Comment by altaiezior** [comment]
@bm1549 the images are published closing the issue.

**Comment by altaiezior** [comment]
@bm1549 let me know if there are other good images that you can think I can work upon.

@sjucovschi I tried 7.2.0 there are some issues happening will get back on this.

**Comment by sjucovschi** [comment]
@anuragagarwal561994 let me know if there's anything I can help with
